# Generated by Django 4.2.6 on 2023-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_basic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basic',
        ),
    ]
