# Generated by Django 4.2.6 on 2023-10-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_title_remove_image_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='files/originals/'),
        ),
    ]
