# Generated by Django 4.2.6 on 2023-10-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_image_file_alter_image_original_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='expiring_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
